/* Kunsang Gar administration */
(async function () {
  const load = (src) => new Promise((resolve, reject) => { const script = document.createElement("script"); script.src = src; script.onload = resolve; script.onerror = reject; document.head.appendChild(script); });
  if (!window.KUNSANG_GAR_CONFIG) await load("/assets/platform-config.js?v=22caf6a");
  if (!window.supabase) await load("https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2");
  if (!window.KunsangGar) await load("/assets/platform.js?v=copy-cleanup-v1");
  const api = window.KunsangGar;
  const client = api?.client;
  const page = document.body.dataset.page || "overview";
  const app = document.getElementById("admin-app");
  const state = { programs: [], content: [] };
  const esc = api?.esc || ((v) => String(v ?? ""));
  const field = (label, name, type = "text", value = "", options = []) => {
    const control = type === "textarea" ? `<textarea name="${name}" rows="4">${esc(value)}</textarea>` : type === "select" ? `<select name="${name}">${options.map((option) => { const [optionValue, optionLabel] = Array.isArray(option) ? option : [option, option]; return `<option value="${optionValue}" ${optionValue === value ? "selected" : ""}>${optionLabel}</option>`; }).join("")}</select>` : `<input name="${name}" type="${type}" value="${esc(value)}" ${name === "title" ? "required" : ""}>`;
    return `<label class="field">${label}${control}</label>`;
  };
  const shell = (body, current) => `<div class="admin-shell"><aside class="admin-sidebar"><a class="admin-brand" href="/admin/"><img src="/assets/kunsaanglogo.jpg" alt=""><span>Kunsang Gar</span></a><nav class="admin-nav">${[["Inicio","index.html","overview"],["Programas","programs.html","programs"],["Contenidos","content.html","content"],["Alumnos","students.html","students"],["Accesos","access.html","access"],["Pagos","orders.html","orders"],["Biblioteca","library.html","library"]].map(([label, href, id]) => `<a href="/admin/${href}" ${current === id ? "aria-current=page" : ""}>${label}</a>`).join("")}</nav><div class="sidebar-actions"><a class="side-link" href="/account/">Área de estudiantes</a></div></aside><div class="admin-main"><header class="admin-topbar"><button class="icon-button mobile-menu" type="button" data-menu aria-label="Abrir menú">☰</button><span class="admin-runtime">Administración</span><button class="btn secondary small" type="button" data-logout>Cerrar sesión</button></header><main class="page" id="main">${body}</main></div></div><div class="toast" id="toast" role="status" aria-live="polite"></div>`;
  const head = (title, action = "") => `<div class="page-head"><h1>${title}</h1><div class="actions">${action}</div></div>`;
  const table = (headers, rows) => `<div class="card table-wrap"><table><thead><tr>${headers.map((h) => `<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.join("")}</tbody></table></div>`;
  const toast = (message, error = false) => { const el = document.getElementById("toast"); if (!el) return; el.textContent = message; el.dataset.status = error ? "error" : "ok"; el.classList.add("is-visible"); setTimeout(() => el.classList.remove("is-visible"), 2600); };
  const displayValue = (value) => ({ PUBLIC: "Público", ENROLLED: "Alumnos inscritos", RESTRICTED: "Acceso individual", DRAFT: "Borrador", PUBLISHED: "Publicado", ACTIVE: "Activo", CANCELLED: "Cancelado", APPROVED: "Autorizado", DENIED: "No autorizado", PENDING: "Pendiente", ADMIN: "Administrador", PRACTITIONER: "Estudiante", VIDEO: "Video", AUDIO: "Audio", PDF: "PDF", TEXT: "Texto", OTHER: "Recurso", approved: "Aprobado", pending: "Pendiente", rejected: "Rechazado", cancelled: "Cancelado", refunded: "Reembolsado", in_process: "En proceso", in_mediation: "En revisión", charged_back: "Revertido", authorized: "Autorizado", unknown: "Pendiente" }[value] || value || "—");
  const accessBadge = (value) => `<span class="badge">${esc(displayValue(value))}</span>`;
  async function getPrograms() { const { data, error } = await client.from("programs").select("*").order("created_at", { ascending: false }); if (error) throw error; state.programs = data || []; return state.programs; }
  async function getContent() { const { data, error } = await client.from("content_items").select("*, programs(title)").order("created_at", { ascending: false }); if (error) throw error; state.content = data || []; return state.content; }
  async function saveProgram(event) { event.preventDefault(); const form = event.currentTarget; const id = form.dataset.id || null; const session = await api.current(); const values = Object.fromEntries(new FormData(form)); const row = { ...(id ? { id } : {}), title: values.title, slug: values.slug || api.slugify(values.title), description: values.description || null, teacher: values.teacher || null, level: values.level || null, format: values.format || null, access_level: values.access_level, status: values.status, cover_image_url: values.cover_image_url || null, created_by: session.user.id }; const { error } = await client.from("programs").upsert(row).select().single(); if (error) throw error; toast(id ? "Programa actualizado." : "Programa guardado."); setTimeout(() => location.href = "/admin/programs.html", 500); }
  async function saveContent(event) { event.preventDefault(); const form = event.currentTarget; const id = form.dataset.id || null; const session = await api.current(); const values = Object.fromEntries(new FormData(form)); let storagePath = form.dataset.storagePath || null; const file = form.querySelector("input[name=file]")?.files?.[0]; if (file) { const safeName = file.name.toLowerCase().replace(/[^a-z0-9._-]+/g, "-"); storagePath = `content/${crypto.randomUUID()}-${safeName}`; const upload = await client.storage.from(api.bucket).upload(storagePath, file, { upsert: false, contentType: file.type || "application/octet-stream" }); if (upload.error) throw upload.error; } const row = { ...(id ? { id } : {}), program_id: values.program_id, title: values.title, description: values.description || null, content_type: values.content_type, access_level: values.access_level, status: values.status, storage_path: storagePath, external_url: values.external_url || null, created_by: session.user.id }; const { error } = await client.from("content_items").upsert(row).select().single(); if (error) throw error; toast(id ? "Contenido actualizado." : "Contenido guardado."); setTimeout(() => location.href = "/admin/content.html", 500); }
  async function toggle(tableName, id, statusValue) { const { error } = await client.from(tableName).update({ status: statusValue }).eq("id", id); if (error) throw error; location.reload(); }
  function overview() { return head("Panel") + `<div data-platform-status class="notice" hidden></div><section class="grid two-grid"><article class="card card-pad"><h2>Programas</h2><strong id="program-count">—</strong><div style="margin-top:16px"><a class="btn" href="/admin/program-editor.html">Crear programa</a></div></article><article class="card card-pad"><h2>Contenidos</h2><strong id="content-count">—</strong><div style="margin-top:16px"><a class="btn" href="/admin/content.html?new=1">Agregar contenido</a></div></article></section>`; }
  function programs() { return head("Programas", `<a class="btn" href="/admin/program-editor.html">Crear programa</a>`) + `<div data-platform-status class="notice" hidden></div><div id="program-table"><div class="card card-pad">Cargando…</div></div>`; }
  function programEditor() { const id = new URLSearchParams(location.search).get("id"); return head(id ? "Editar programa" : "Crear programa") + `<div data-platform-status class="notice" hidden></div><form class="card card-pad" data-program-form data-id="${esc(id || "")}"><div class="form-grid">${field("Título", "title")} ${field("Descripción", "description", "textarea")} ${field("Maestro / equipo", "teacher")} ${field("Nivel", "level", "select", "Beginner", [["Beginner", "Inicial"], ["Intermediate", "Intermedio"], ["Advanced", "Avanzado"]])} ${field("Formato", "format", "select", "Online", [["Online", "En línea"], ["In person", "Presencial"], ["Hybrid", "Híbrido"], ["Self-paced", "A tu ritmo"]])} ${field("Visibilidad", "access_level", "select", "PUBLIC", [["PUBLIC", "Público"], ["ENROLLED", "Alumnos inscritos"], ["RESTRICTED", "Acceso individual"]])} ${field("Estado", "status", "select", "DRAFT", [["DRAFT", "Borrador"], ["PUBLISHED", "Publicado"]])} ${field("Imagen de portada", "cover_image_url", "url")}</div><div class="actions" style="margin-top:18px"><button class="btn" type="submit">Guardar</button><a class="btn secondary" href="/admin/programs.html">Cancelar</a></div></form>`; }
  function content() { return head("Contenidos", `<a class="btn" href="/admin/content.html?new=1">Agregar contenido</a>`) + `<div data-platform-status class="notice" hidden></div><div id="content-table"><div class="card card-pad">Cargando…</div></div>`; }
  function contentForm(item = {}) { const programOptions = state.programs.map((p) => `<option value="${p.id}" ${p.id === item.program_id ? "selected" : ""}>${esc(p.title)}</option>`).join(""); return `<form class="card card-pad" data-content-form data-id="${esc(item.id || "")}" data-storage-path="${esc(item.storage_path || "")}" style="margin-top:16px"><h2>${item.id ? "Editar contenido" : "Agregar contenido"}</h2><div class="form-grid">${field("Título", "title", "text", item.title || "")} <label class="field">Programa<select name="program_id" required>${programOptions}</select></label> ${field("Descripción", "description", "textarea", item.description || "")} ${field("Tipo", "content_type", "select", item.content_type || "PDF", [["VIDEO", "Video"], ["AUDIO", "Audio"], ["PDF", "PDF"], ["TEXT", "Texto"], ["OTHER", "Otro"]])} ${field("Visibilidad", "access_level", "select", item.access_level || "PUBLIC", [["PUBLIC", "Público"], ["ENROLLED", "Alumnos inscritos"], ["RESTRICTED", "Acceso individual"]])} ${field("Estado", "status", "select", item.status || "DRAFT", [["DRAFT", "Borrador"], ["PUBLISHED", "Publicado"]])} ${field("Enlace del recurso", "external_url", "url", item.external_url || "")} <label class="field">Archivo<input name="file" type="file" accept="audio/*,video/*,application/pdf,text/plain"></label></div><button class="btn" type="submit">Guardar</button></form>`; }
  function events() { return head("Eventos"); }
  function orders() { return head("Pagos") + `<div data-platform-status class="notice" hidden></div><div id="orders-table"><div class="card card-pad">Cargando…</div></div>`; }
  function libraryAdmin() { return head("Biblioteca", `<a class="btn" href="/admin/content.html">Ver contenidos</a>`); }
  async function getStudents() { const { data, error } = await client.from("profiles").select("id,full_name,role,created_at").eq("role", "PRACTITIONER").order("created_at", { ascending: false }); if (error) throw error; return data || []; }
  async function getAccounts() { const { data, error } = await client.from("profiles").select("id,full_name,role,created_at").order("created_at", { ascending: true }); if (error) throw error; return data || []; }
  async function getEnrollments() { const { data, error } = await client.from("enrollments").select("id,user_id,program_id,status,programs(title)").order("created_at", { ascending: false }); if (error) throw error; return data || []; }
  async function getGrants() { const { data, error } = await client.from("access_grants").select("id,user_id,content_item_id,status,content_items(title)").order("created_at", { ascending: false }); if (error) throw error; return data || []; }
  async function saveEnrollment(event) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); const { error } = await client.from("enrollments").upsert({ user_id: values.user_id, program_id: values.program_id, status: "ACTIVE" }, { onConflict: "user_id,program_id" }); if (error) throw error; toast("Alumno incorporado al programa."); setTimeout(() => location.reload(), 500); }
  async function saveGrant(event) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); const { error } = await client.from("access_grants").upsert({ user_id: values.user_id, content_item_id: values.content_item_id, status: values.status, decided_by: (await api.current()).user.id, decided_at: new Date().toISOString() }, { onConflict: "user_id,content_item_id" }); if (error) throw error; toast("Acceso actualizado."); setTimeout(() => location.reload(), 500); }
  async function saveRole(event) { event.preventDefault(); const form = event.currentTarget; const session = await api.current(); const userId = form.dataset.userId; const role = form.elements.role.value; if (!userId || !["ADMIN", "PRACTITIONER"].includes(role)) throw new Error("Permiso no válido."); if (userId === session?.user?.id) throw new Error("No puedes cambiar tus propios permisos."); const { data: accounts, error: listError } = await client.from("profiles").select("id,role"); if (listError) throw listError; const admins = (accounts || []).filter((item) => item.role === "ADMIN"); const target = (accounts || []).find((item) => item.id === userId); if (target?.role === "ADMIN" && role !== "ADMIN" && admins.length <= 1) throw new Error("No puedes retirar el acceso del último administrador."); const { error } = await client.from("profiles").update({ role }).eq("id", userId); if (error) throw error; toast("Permisos actualizados."); setTimeout(() => location.reload(), 600); }
  function students() { return head("Alumnos") + `<div data-platform-status class="notice" hidden></div><div id="students-table" class="card table-wrap">Cargando…</div><h2 style="margin-top:24px">Inscribir en programa</h2><form class="card card-pad form-grid" data-enrollment-form><label class="field">Alumno<select name="user_id" id="student-user" required></select></label><label class="field">Programa<select name="program_id" id="student-program" required></select></label><button class="btn" type="submit">Inscribir</button></form>`; }
  function access() { return head("Accesos") + `<div data-platform-status class="notice" hidden></div><div id="grants-table" class="card table-wrap">Cargando…</div><h2 style="margin-top:24px">Asignar acceso</h2><form class="card card-pad form-grid" data-grant-form><label class="field">Alumno<select name="user_id" id="grant-user" required></select></label><label class="field">Contenido<select name="content_item_id" id="grant-content" required></select></label><label class="field">Permiso<select name="status"><option value="APPROVED">Autorizar</option><option value="DENIED">Denegar</option></select></label><button class="btn" type="submit">Guardar</button></form>`; }
  async function renderData() {
    if (page === "overview") { const [programRows, contentRows] = await Promise.all([getPrograms(), getContent()]); document.getElementById("program-count").textContent = programRows.length; document.getElementById("content-count").textContent = contentRows.length; return; }
    if (page === "programs") { const rows = await getPrograms(); document.getElementById("program-table").innerHTML = table(["Programa", "Visibilidad", "Estado", "Actualizado", "Acciones"], rows.map((p) => `<tr><td><strong>${esc(p.title)}</strong></td><td>${accessBadge(p.access_level)}</td><td>${accessBadge(p.status)}</td><td>${api.fmtDate(p.updated_at)}</td><td><a class="link-button" href="/admin/program-editor.html?id=${p.id}">Editar</a> <button class="link-button" data-toggle-program="${p.id}" data-status="${p.status === "PUBLISHED" ? "DRAFT" : "PUBLISHED"}">${p.status === "PUBLISHED" ? "Retirar" : "Publicar"}</button></td></tr>`)); return; }
    if (page === "content") { const [programRows, items] = await Promise.all([getPrograms(), getContent()]); let html = table(["Contenido", "Programa", "Tipo", "Visibilidad", "Estado", "Acciones"], items.map((item) => `<tr><td><strong>${esc(item.title)}</strong></td><td>${esc(item.programs?.title || programRows.find((p) => p.id === item.program_id)?.title || "—")}</td><td>${accessBadge(item.content_type)}</td><td>${accessBadge(item.access_level)}</td><td>${accessBadge(item.status)}</td><td><a class="link-button" href="/admin/content.html?edit=${item.id}">Editar</a> <button class="link-button" data-publish-content="${item.id}" data-status="${item.status === "PUBLISHED" ? "DRAFT" : "PUBLISHED"}">${item.status === "PUBLISHED" ? "Retirar" : "Publicar"}</button></td></tr>`)); const editId = new URLSearchParams(location.search).get("edit"); const editItem = items.find((item) => item.id === editId); if (editItem || new URLSearchParams(location.search).get("new") === "1") html += contentForm(editItem || {}); document.getElementById("content-table").innerHTML = html; document.querySelector("[data-content-form]")?.addEventListener("submit", (e) => saveContent(e).catch((x) => { api.fail(x); toast("No se pudo guardar el contenido.", true); })); return; }
    if (page === "students") {
      const [studentsRows, accounts, programsRows, enrollments] = await Promise.all([getStudents(), getAccounts(), getPrograms(), getEnrollments()]);
      const session = await api.current();
      document.getElementById("students-table").innerHTML = accounts.length ? table(["Cuenta", "Perfil", "Registro", "Programas", "Permisos"], accounts.map((account) => {
        const self = account.id === session?.user?.id;
        const onlyAdmin = account.role === "ADMIN" && accounts.filter((item) => item.role === "ADMIN").length <= 1;
        const options = [["PRACTITIONER", "Estudiante"], ["ADMIN", "Administrador"]].map(([role, label]) => `<option value="${role}" ${role === account.role ? "selected" : ""}>${label}</option>`).join("");
        const select = self || onlyAdmin ? accessBadge(account.role) : `<form data-role-form data-user-id="${esc(account.id)}" class="row-actions"><select name="role" aria-label="Permisos de ${esc(account.full_name || "esta cuenta")}">${options}</select><button class="btn secondary small" type="submit">Guardar</button></form>`;
        return `<tr><td><strong>${esc(account.full_name || "Cuenta sin nombre")}</strong></td><td>${accessBadge(account.role)}</td><td>${api.fmtDate(account.created_at)}</td><td>${esc(enrollments.filter((e) => e.user_id === account.id && e.status === "ACTIVE").map((e) => e.programs?.title || "").filter(Boolean).join(", ") || "—")}</td><td>${select}</td></tr>`;
      })) : `<div class="card-pad">Aún no hay cuentas.</div>`;
      const fill = (id, rows, label) => {
        const el = document.getElementById(id);
        el.innerHTML = rows.map((row) => `<option value="${row.id}">${esc(row.full_name || row.title || "")}</option>`).join("");
        if (!rows.length) el.innerHTML = `<option value="">${label}</option>`;
      };
      fill("student-user", studentsRows, "No hay alumnos disponibles");
      fill("student-program", programsRows, "No hay programas disponibles");
      document.querySelector("[data-enrollment-form]")?.addEventListener("submit", (e) => saveEnrollment(e).catch((x) => { api.fail(x); toast("No se pudo guardar.", true); }));
      document.querySelectorAll("[data-role-form]").forEach((form) => form.addEventListener("submit", (e) => saveRole(e).catch((x) => { api.fail(x); toast("No se pudieron actualizar los permisos.", true); })));
      return;
    }
    if (page === "access") { const [studentsRows, contentRows, grants] = await Promise.all([getStudents(), getContent(), getGrants()]); document.getElementById("grants-table").innerHTML = grants.length ? table(["Alumno", "Contenido", "Permiso"], grants.map((grant) => `<tr><td>${esc(studentsRows.find((student) => student.id === grant.user_id)?.full_name || "Estudiante")}</td><td>${esc(grant.content_items?.title || "Recurso")}</td><td>${accessBadge(grant.status)}</td></tr>`)) : `<div class="card-pad">Aún no hay accesos asignados.</div>`; const fill = (id, rows, label) => { const el = document.getElementById(id); el.innerHTML = rows.map((row) => `<option value="${row.id}">${esc(row.full_name || row.title || "")}</option>`).join(""); if (!rows.length) el.innerHTML = `<option value="">${label}</option>`; }; fill("grant-user", studentsRows, "No hay alumnos disponibles"); fill("grant-content", contentRows, "No hay contenidos disponibles"); document.querySelector("[data-grant-form]")?.addEventListener("submit", (e) => saveGrant(e).catch((x) => { api.fail(x); toast("No se pudo guardar.", true); })); return; }
    if (page === "orders") { const { data, error } = await client.from("ticket_orders").select("id,created_at,event_slug,event_name,total_amount,currency_code,payment_status,payment_id,external_reference").order("created_at", { ascending: false }).limit(100); if (error) throw error; const money = new Intl.NumberFormat("es-MX", { style: "currency", currency: "MXN" }); const dateTime = (value) => value ? new Intl.DateTimeFormat("es-MX", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—"; const rows = (data || []).map((order) => `<tr><td>${esc(dateTime(order.created_at))}</td><td>${esc(order.event_name || "Evento")}</td><td>${esc(money.format(Number(order.total_amount || 0)))}</td><td>${accessBadge(order.payment_status || "pending")}</td></tr>`); document.getElementById("orders-table").innerHTML = rows.length ? table(["Fecha", "Evento", "Monto", "Estado"], rows) : `<div class="card card-pad">Aún no hay pagos.</div>`; return; }
    if (page === "program-editor") { const id = new URLSearchParams(location.search).get("id"); if (id) { const { data, error } = await client.from("programs").select("*").eq("id", id).single(); if (error) throw error; const form = document.querySelector("[data-program-form]"); Object.entries(data).forEach(([key, value]) => { if (form.elements[key]) form.elements[key].value = value ?? ""; }); } }
  }
  async function init() {
    const adminAccess = await api.guard("ADMIN");
    if (!adminAccess) return;
    app.innerHTML = shell(({ overview, programs, "program-editor": programEditor, content, students, events, orders, library: libraryAdmin, access }[page] || overview)(), page);
    document.querySelector("[data-menu]")?.addEventListener("click", () => document.querySelector(".admin-sidebar")?.classList.toggle("is-open"));
    document.querySelectorAll("[data-logout]").forEach((el) => el.addEventListener("click", async () => { await client?.auth.signOut(); location.href = "/admin/login/"; }));
    if (!client) { api.status("No fue posible abrir el panel. Inténtalo más tarde.", "error"); return; }
    try { if (page === "program-editor") document.querySelector("[data-program-form]")?.addEventListener("submit", (e) => saveProgram(e).catch((x) => { api.fail(x); toast("No se pudo guardar el programa.", true); })); await renderData(); document.addEventListener("click", (e) => { const p = e.target.closest("[data-toggle-program]"); const c = e.target.closest("[data-publish-content]"); if (p) toggle("programs", p.dataset.toggleProgram, p.dataset.status).catch((x) => toast("No se pudo actualizar el programa.", true)); if (c) toggle("content_items", c.dataset.publishContent, c.dataset.status).catch((x) => toast("No se pudo actualizar el contenido.", true)); }); } catch (error) { api.fail(error); toast("No se pudo cargar la información.", true); }
  }
  init();
})();
