/* ROOT admin: real Supabase CRUD for the V1 golden path. */
(async function () {
  const load = (src) => new Promise((resolve, reject) => { const script = document.createElement("script"); script.src = src; script.onload = resolve; script.onerror = reject; document.head.appendChild(script); });
  if (!window.KUNSANG_GAR_CONFIG) await load("/assets/platform-config.js");
  if (!window.supabase) await load("https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2");
  if (!window.KunsangGar) await load("/assets/platform.js");
  const api = window.KunsangGar;
  const client = api?.client;
  const page = document.body.dataset.page || "overview";
  const app = document.getElementById("admin-app");
  const state = { programs: [], content: [] };
  const esc = api?.esc || ((v) => String(v ?? ""));
  const field = (label, name, type = "text", value = "", options = []) => {
    const control = type === "textarea" ? `<textarea name="${name}" rows="4">${esc(value)}</textarea>` : type === "select" ? `<select name="${name}">${options.map((o) => `<option value="${o}" ${o === value ? "selected" : ""}>${o}</option>`).join("")}</select>` : `<input name="${name}" type="${type}" value="${esc(value)}" ${name === "title" ? "required" : ""}>`;
    return `<label class="field">${label}${control}</label>`;
  };
  const shell = (body, current) => `<div class="admin-shell"><aside class="admin-sidebar"><a class="admin-brand" href="/index.html"><img src="/assets/kunsaanglogo.jpg" alt=""><span>Kunsang Gar Mexico<br>Administration</span></a><nav class="admin-nav">${[["Overview","index.html","overview"],["Programs","programs.html","programs"],["Content","content.html","content"],["Events","events.html","events"],["Digital Library","library.html","library"],["Access Control","access.html","access"]].map(([label, href, id]) => `<a href="/admin/${href}" ${current === id ? "aria-current=page" : ""}>${label}</a>`).join("")}</nav><div class="sidebar-actions"><a class="side-link" href="/account/">View practitioner area</a></div></aside><div class="admin-main"><header class="admin-topbar"><button class="icon-button mobile-menu" type="button" data-menu>Menu</button><span class="admin-runtime">Supabase V1 · ${esc(api?.cfg?.supabaseUrl ? "conectado" : "sin configurar")}</span><button class="btn secondary small" type="button" data-logout>Salir</button></header><main class="page" id="main">${body}</main></div></div><div class="toast" id="toast" role="status" aria-live="polite"></div>`;
  const head = (kicker, title, copy, action = "") => `<div class="crumbs"><a href="/admin/">Administration</a><span>/</span><span>${kicker}</span></div><div class="page-head"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${copy}</p></div><div class="actions">${action}</div></div>`;
  const table = (headers, rows) => `<div class="card table-wrap"><table><thead><tr>${headers.map((h) => `<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.join("")}</tbody></table></div>`;
  const toast = (message, error = false) => { const el = document.getElementById("toast"); if (!el) return; el.textContent = message; el.dataset.status = error ? "error" : "ok"; el.classList.add("is-visible"); setTimeout(() => el.classList.remove("is-visible"), 2600); };
  const accessBadge = (value) => `<span class="badge">${esc(value)}</span>`;
  async function getPrograms() { const { data, error } = await client.from("programs").select("*").order("created_at", { ascending: false }); if (error) throw error; state.programs = data || []; return state.programs; }
  async function getContent() { const { data, error } = await client.from("content_items").select("*, programs(title)").order("created_at", { ascending: false }); if (error) throw error; state.content = data || []; return state.content; }
  async function saveProgram(event) { event.preventDefault(); const form = event.currentTarget; const id = form.dataset.id || null; const session = await api.current(); const values = Object.fromEntries(new FormData(form)); const row = { ...(id ? { id } : {}), title: values.title, slug: values.slug || api.slugify(values.title), description: values.description || null, teacher: values.teacher || null, level: values.level || null, format: values.format || null, access_level: values.access_level, status: values.status, cover_image_url: values.cover_image_url || null, created_by: session.user.id }; const { error } = await client.from("programs").upsert(row).select().single(); if (error) throw error; toast(id ? "Programa actualizado y persistido." : "Programa creado y persistido."); setTimeout(() => location.href = "/admin/programs.html", 500); }
  async function saveContent(event) { event.preventDefault(); const form = event.currentTarget; const id = form.dataset.id || null; const session = await api.current(); const values = Object.fromEntries(new FormData(form)); const row = { ...(id ? { id } : {}), program_id: values.program_id, title: values.title, description: values.description || null, content_type: values.content_type, access_level: values.access_level, status: values.status, storage_path: values.storage_path || null, external_url: values.external_url || null, created_by: session.user.id }; const { error } = await client.from("content_items").upsert(row).select().single(); if (error) throw error; toast(id ? "Contenido actualizado y persistido." : "Contenido creado y persistido."); setTimeout(() => location.href = "/admin/content.html", 500); }
  async function toggle(tableName, id, statusValue) { const { error } = await client.from(tableName).update({ status: statusValue }).eq("id", id); if (error) throw error; location.reload(); }
  function overview() { return head("Overview", "Administración V1", "Golden path real: programas y contenido en Supabase, protegidos por rol y RLS.", `<a class="btn" href="/admin/program-editor.html">Crear programa</a>`) + `<div data-platform-status class="notice" hidden></div><section class="grid two-grid"><article class="card card-pad"><h2>Estado</h2><p>Las pantallas de ROOT ya no dependen de datos hardcodeados para el flujo principal.</p><div class="list"><div class="list-row"><strong>Programas</strong><span id="program-count">—</span></div><div class="list-row"><strong>Contenido</strong><span id="content-count">—</span></div></div></article><article class="card card-pad"><h2>Operación</h2><p>Publica un programa, asócialo con contenido y asigna PUBLIC, ENROLLED o RESTRICTED.</p><a class="btn secondary" href="/admin/content.html?new=1">Gestionar contenido</a></article></section>`; }
  function programs() { return head("Programs", "Programas", "Crear, editar, publicar y despublicar programas persistidos.", `<a class="btn" href="/admin/program-editor.html">Crear programa</a>`) + `<div data-platform-status class="notice" hidden></div><div id="program-table"><div class="card card-pad">Cargando programas…</div></div>`; }
  function programEditor() { const id = new URLSearchParams(location.search).get("id"); return head("Programs", id ? "Editar programa" : "Crear programa", "Los cambios se guardan en public.programs.") + `<div data-platform-status class="notice" hidden></div><form class="card card-pad editor-layout" data-program-form data-id="${esc(id || "")}"><div><div class="form-grid">${field("Título", "title")} ${field("Slug", "slug")} ${field("Descripción", "description", "textarea")} ${field("Maestro / equipo", "teacher")} ${field("Nivel", "level", "select", "Beginner", ["Beginner", "Intermediate", "Advanced"])} ${field("Formato", "format", "select", "Online", ["Online", "In person", "Hybrid", "Self-paced"])} ${field("Acceso", "access_level", "select", "PUBLIC", ["PUBLIC", "ENROLLED", "RESTRICTED"])} ${field("Estado", "status", "select", "DRAFT", ["DRAFT", "PUBLISHED"])} ${field("Cover URL", "cover_image_url", "url")}</div><div class="actions" style="margin-top:18px"><button class="btn" type="submit">Guardar programa</button><a class="btn secondary" href="/admin/programs.html">Cancelar</a></div></div><aside class="card card-pad"><h2>Control</h2><p>PUBLIC es visible; ENROLLED requiere inscripción; RESTRICTED requiere grant aprobado.</p></aside></form>`; }
  function content() { return head("Content", "Contenido", "Crear, editar y publicar recursos asociados a programas.", `<a class="btn" href="/admin/content.html?new=1">Crear contenido</a>`) + `<div data-platform-status class="notice" hidden></div><div id="content-table"><div class="card card-pad">Cargando contenido…</div></div>`; }
  function contentForm(item = {}) { const programOptions = state.programs.map((p) => `<option value="${p.id}" ${p.id === item.program_id ? "selected" : ""}>${esc(p.title)}</option>`).join(""); return `<form class="card card-pad" data-content-form data-id="${esc(item.id || "")}" style="margin-top:16px"><h2>${item.id ? "Editar contenido" : "Nuevo contenido"}</h2><div class="form-grid">${field("Título", "title", "text", item.title || "")} <label class="field">Programa<select name="program_id" required>${programOptions}</select></label> ${field("Descripción", "description", "textarea", item.description || "")} ${field("Tipo", "content_type", "select", item.content_type || "PDF", ["VIDEO", "AUDIO", "PDF", "TEXT", "OTHER"])} ${field("Acceso", "access_level", "select", item.access_level || "PUBLIC", ["PUBLIC", "ENROLLED", "RESTRICTED"])} ${field("Estado", "status", "select", item.status || "DRAFT", ["DRAFT", "PUBLISHED"])} ${field("Ruta Storage privada", "storage_path", "text", item.storage_path || "")} ${field("URL externa", "external_url", "url", item.external_url || "")}</div><p class="meta">Para un archivo protegido usa la ruta dentro del bucket privado protected-content; no lo coloques en /assets.</p><button class="btn" type="submit">Guardar contenido</button></form>`; }
  function events() { return head("Events", "Eventos", "La administración de eventos queda preservada en su integración existente.") + `<div data-platform-status class="notice">Eventos BD: NOT_IMPLEMENTED en V1; la landing-eventos y ticket_orders no fueron modificados.</div>`; }
  function libraryAdmin() { return head("Library", "Biblioteca", "La biblioteca pública se alimenta de content_items y sus permisos.") + `<div data-platform-status class="notice">Usa Contenido para publicar recursos. La biblioteca ROOT resuelve acceso con RLS y signed URLs.</div>`; }
  function access() { return head("Access", "Control de acceso", "Los grants restringidos se administran directamente en Supabase en V1.") + `<div data-platform-status class="notice">UI de aprobación P1: NOT_IMPLEMENTED. La base access_grants y RLS están preparadas.</div>`; }
  async function renderData() {
    if (page === "overview") { const [programRows, contentRows] = await Promise.all([getPrograms(), getContent()]); document.getElementById("program-count").textContent = programRows.length; document.getElementById("content-count").textContent = contentRows.length; return; }
    if (page === "programs") { const rows = await getPrograms(); document.getElementById("program-table").innerHTML = table(["Programa", "Acceso", "Estado", "Actualizado", "Acciones"], rows.map((p) => `<tr><td><strong>${esc(p.title)}</strong><div class="meta">${esc(p.slug)}</div></td><td>${accessBadge(p.access_level)}</td><td>${accessBadge(p.status)}</td><td>${api.fmtDate(p.updated_at)}</td><td><a class="link-button" href="/admin/program-editor.html?id=${p.id}">Editar</a> <button class="link-button" data-toggle-program="${p.id}" data-status="${p.status === "PUBLISHED" ? "DRAFT" : "PUBLISHED"}">${p.status === "PUBLISHED" ? "Despublicar" : "Publicar"}</button></td></tr>`)); return; }
    if (page === "content") { const [programRows, items] = await Promise.all([getPrograms(), getContent()]); let html = table(["Título", "Programa", "Tipo", "Acceso", "Estado", "Acciones"], items.map((item) => `<tr><td><strong>${esc(item.title)}</strong></td><td>${esc(item.programs?.title || programRows.find((p) => p.id === item.program_id)?.title || "—")}</td><td>${esc(item.content_type)}</td><td>${accessBadge(item.access_level)}</td><td>${accessBadge(item.status)}</td><td><a class="link-button" href="/admin/content.html?edit=${item.id}">Editar</a> <button class="link-button" data-publish-content="${item.id}" data-status="${item.status === "PUBLISHED" ? "DRAFT" : "PUBLISHED"}">${item.status === "PUBLISHED" ? "Despublicar" : "Publicar"}</button></td></tr>`)); const editId = new URLSearchParams(location.search).get("edit"); const editItem = items.find((item) => item.id === editId); if (editItem || new URLSearchParams(location.search).get("new") === "1") html += contentForm(editItem || {}); document.getElementById("content-table").innerHTML = html; document.querySelector("[data-content-form]")?.addEventListener("submit", (e) => saveContent(e).catch((x) => { api.fail(x); toast(x.message, true); })); return; }
    if (page === "program-editor") { const id = new URLSearchParams(location.search).get("id"); if (id) { const { data, error } = await client.from("programs").select("*").eq("id", id).single(); if (error) throw error; const form = document.querySelector("[data-program-form]"); Object.entries(data).forEach(([key, value]) => { if (form.elements[key]) form.elements[key].value = value ?? ""; }); } }
  }
  async function init() {
    app.innerHTML = shell(({ overview, programs, "program-editor": programEditor, content, events, library: libraryAdmin, access }[page] || overview)(), page);
    document.querySelector("[data-menu]")?.addEventListener("click", () => document.querySelector(".admin-sidebar")?.classList.toggle("is-open"));
    document.querySelectorAll("[data-logout]").forEach((el) => el.addEventListener("click", async () => { await client?.auth.signOut(); location.href = "/account/"; }));
    if (!client) { api.status("Supabase no está configurado. Esta ruta está bloqueada hasta cargar la configuración runtime.", "error"); return; }
    try { if (page === "program-editor") document.querySelector("[data-program-form]")?.addEventListener("submit", (e) => saveProgram(e).catch((x) => { api.fail(x); toast(x.message, true); })); await renderData(); document.addEventListener("click", (e) => { const p = e.target.closest("[data-toggle-program]"); const c = e.target.closest("[data-publish-content]"); if (p) toggle("programs", p.dataset.toggleProgram, p.dataset.status).catch((x) => toast(x.message, true)); if (c) toggle("content_items", c.dataset.publishContent, c.dataset.status).catch((x) => toast(x.message, true)); }); } catch (error) { api.fail(error); toast(error.message, true); }
  }
  init();
})();
